package equipment

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/mediflow/backend/internal/shared/models"
	"github.com/redis/go-redis/v9"
	"github.com/rs/zerolog/log"
	"github.com/skip2/go-qrcode"
)

type Service interface {
	CreateItem(ctx context.Context, item *models.EquipmentItem) error
	GetItem(ctx context.Context, tenantID, itemID uuid.UUID) (*models.EquipmentItem, error)
	ListItems(ctx context.Context, tenantID uuid.UUID, filters map[string]interface{}, offset, limit int) ([]models.EquipmentItem, error)
	UpdateStatus(ctx context.Context, tenantID, itemID uuid.UUID, newStatus models.EquipmentStatus, locationID *uuid.UUID, userID uuid.UUID, reason string) error
	UpdateStatusByQR(ctx context.Context, qrCode string, newStatus models.EquipmentStatus, locationID *uuid.UUID, userID uuid.UUID, reason string) error
	GetAvailabilitySummary(ctx context.Context, tenantID uuid.UUID) ([]map[string]interface{}, error)
	GetStatusHistory(ctx context.Context, tenantID, itemID uuid.UUID, limit, offset int) ([]models.EquipmentStatusLog, error)
}

type equipmentService struct {
	repo            Repository
	redisClient     *redis.Client
	availabilityMgr *AvailabilityManager
}

func NewService(repo Repository, redisClient *redis.Client, availabilityMgr *AvailabilityManager) Service {
	return &equipmentService{
		repo:            repo,
		redisClient:     redisClient,
		availabilityMgr: availabilityMgr,
	}
}

func (s *equipmentService) CreateItem(ctx context.Context, item *models.EquipmentItem) error {
	// 1. Generate QR Code if not provided (usually generated by system)
	if item.QRCode == "" {
		item.QRCode = fmt.Sprintf("MF-%s-%s", item.TenantID.String()[:8], uuid.New().String()[:8])
	}

	// 2. Initial status
	if item.Status == "" {
		item.Status = models.StatusAvailable
	}

	// 3. Create in DB
	err := s.repo.Create(ctx, item)
	if err != nil {
		return err
	}

	// 4. Invalidate Redis cache
	s.invalidateCache(ctx, item.TenantID)

	return nil
}

func (s *equipmentService) GetItem(ctx context.Context, tenantID, itemID uuid.UUID) (*models.EquipmentItem, error) {
	return s.repo.FindByID(ctx, tenantID, itemID)
}

func (s *equipmentService) ListItems(ctx context.Context, tenantID uuid.UUID, filters map[string]interface{}, offset, limit int) ([]models.EquipmentItem, error) {
	return s.repo.FindAll(ctx, tenantID, filters, offset, limit)
}

func (s *equipmentService) UpdateStatus(ctx context.Context, tenantID, itemID uuid.UUID, newStatus models.EquipmentStatus, locationID *uuid.UUID, userID uuid.UUID, reason string) error {
	// 1. Get current item to validate tenant and transition
	item, err := s.repo.FindByID(ctx, tenantID, itemID)
	if err != nil {
		return err
	}

	// 2. Validate state transition
	if !isValidTransition(item.Status, newStatus) {
		return fmt.Errorf("invalid status transition from %s to %s", item.Status, newStatus)
	}

	// 3. Update status in DB (includes logging)
	err = s.repo.UpdateStatus(ctx, itemID, newStatus, locationID, userID, reason)
	if err != nil {
		return err
	}

	// 4. Update real-time availability state
	if item.DepartmentID != nil {
		go func() {
			ctx := context.Background()
			s.availabilityMgr.UpdateCell(ctx, tenantID, *item.DepartmentID, item.CategoryID)
		}()
	}

	return nil
}

func (s *equipmentService) UpdateStatusByQR(ctx context.Context, qrCode string, newStatus models.EquipmentStatus, locationID *uuid.UUID, userID uuid.UUID, reason string) error {
	item, err := s.repo.FindByQRCode(ctx, qrCode)
	if err != nil {
		return err
	}

	return s.UpdateStatus(ctx, item.TenantID, item.ID, newStatus, locationID, userID, reason)
}

func (s *equipmentService) GetAvailabilitySummary(ctx context.Context, tenantID uuid.UUID) ([]map[string]interface{} , error) {
	// Try Redis hash first
	boardKey := fmt.Sprintf("availability_board:%s", tenantID)
	data, err := s.redisClient.HGetAll(ctx, boardKey).Result()
	if err == nil && len(data) > 0 {
		var results []map[string]interface{}
		for _, val := range data {
			var m map[string]interface{}
			json.Unmarshal([]byte(val), &m)
			results = append(results, m)
		}
		return results, nil
	}

	// Fallback to DB
	summary, err := s.repo.GetAvailabilitySummary(ctx, tenantID)
	if err == nil {
		// Async refresh cache
		go s.availabilityMgr.RefreshAll(context.Background(), tenantID)
	}
	return summary, err
}

func (s *equipmentService) GetStatusHistory(ctx context.Context, tenantID, itemID uuid.UUID, limit, offset int) ([]models.EquipmentStatusLog, error) {
	// 1. Verify item belongs to tenant
	_, err := s.repo.FindByID(ctx, tenantID, itemID)
	if err != nil {
		return nil, err
	}

	return s.repo.FindStatusHistory(ctx, itemID, limit, offset)
}

func (s *equipmentService) invalidateCache(ctx context.Context, tenantID uuid.UUID) {
	key := fmt.Sprintf("availability_board:%s", tenantID)
	err := s.redisClient.Del(ctx, key).Err()
	if err != nil {
		log.Error().Err(err).Msg("Failed to invalidate availability cache")
	}
}

func isValidTransition(from, to models.EquipmentStatus) bool {
	if from == to {
		return true
	}

	transitions := map[models.EquipmentStatus][]models.EquipmentStatus{
		models.StatusAvailable: {
			models.StatusInUse,
			models.StatusReserved,
			models.StatusInMaintenance,
			models.StatusInTransit,
			models.StatusMissing,
		},
		models.StatusInUse: {
			models.StatusAvailable,
			models.StatusInMaintenance,
			models.StatusMissing,
		},
		models.StatusReserved: {
			models.StatusInUse,
			models.StatusAvailable,
		},
		models.StatusInMaintenance: {
			models.StatusAvailable,
			models.StatusDecommissioned,
		},
		models.StatusInTransit: {
			models.StatusAvailable,
			models.StatusInUse,
		},
		models.StatusMissing: {
			models.StatusAvailable,
			models.StatusDecommissioned,
		},
	}

	allowed, ok := transitions[from]
	if !ok {
		return false
	}

	for _, a := range allowed {
		if a == to {
			return true
		}
	}

	return false
}

// GenerateQRCodePNG generates a PNG byte array for a QR code
func GenerateQRCodePNG(content string) ([]byte, error) {
	return qrcode.Encode(content, qrcode.Medium, 256)
}
